# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Monogame
      run: dotnet new install MonoGame.Templates.CSharp
      continue-on-error: true
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      continue-on-error: true
      with:
        java-version: '17'
        distribution: 'microsoft'
    
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.0
    
    - name: Set Android SDK 34
      run: echo y | sdkmanager "platforms;android-34"
    
    - name: Restore workloads
      run: dotnet workload restore
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
      
