name: Release App

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Setup Monogame
        run: dotnet new install MonoGame.Templates.CSharp
        continue-on-error: true
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        continue-on-error: true
        with:
          java-version: |
            11
            17
          distribution: 'microsoft'

      - name: Java Version
        run: java -version && echo "JAVA_HOME=${{ env.JAVA_HOME }}"
      
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.0
      
      - name: Set Android SDK 34
        run: echo y | sdkmanager "platforms;android-34"
      
      - name: Restore workloads
        run: |
          dotnet workload restore
          dotnet restore
      
      - name: Build Android
        id: android_build
        run: dotnet publish -c Release -r android-x64 -p:AndroidSdkDirectory="${{ env.ANDROID_SDK_ROOT }}" -p:JavaSdkDirectory=" C:\hostedtoolcache\windows\Java_Microsoft_jdk\11.0.19\x64" Android/Android.csproj

      - name: Sign AAB
        if: ${{ steps.android_build.outcome == 'success' }}
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: Android/bin/Release/net6.0-android/android-x64
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}  

      - name: Report build status
        run: echo "Build status report=${{ job.status }}."

      - name: Upload App Bundle
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}
      