name: "Security Checks"

on:
  push:
    branches: [ "main" ]  
  schedule:
    - cron: '33 23 * * 3'

jobs:
  analyze:
    name: Analyze    
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup Monogame
      run: dotnet new install MonoGame.Templates.CSharp
      continue-on-error: true
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      continue-on-error: true
      with:
        java-version: |
          11
          17
        distribution: 'microsoft'

    - name: Java Version
      run: java -version && echo "JAVA_HOME=${{ env.JAVA_HOME }}"
    
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.0
    
    - name: Set Android SDK 31
      run: echo y | sdkmanager "platforms;android-31"
    
    - name: Restore workloads
      run: |
        dotnet workload restore
        dotnet restore

    - name: Build
      run: dotnet build --no-restore -p:AndroidSdkDirectory="${{ env.ANDROID_SDK_ROOT }}" -p:JavaSdkDirectory=" C:\hostedtoolcache\windows\Java_Microsoft_jdk\11.0.19\x64"

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    - name: Set up Snyk CLI to check for security issues       
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      env:          
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
    - name: Snyk Code test
      run: snyk code test --sarif > snyk-code.sarif
      
    - name: Snyk Open Source monitor
      run: snyk monitor --all-projects

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-code.sarif
