name: "Security Checks"

on:
  push:
    branches: [ "main" ]  
  schedule:
    - cron: '33 23 * * 3'

jobs:
  analyze:
    name: Analyze    
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
  
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    - name: Set up Snyk CLI to check for security issues       
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      env:          
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
    - name: Snyk Code test
      run: snyk code test --sarif > snyk-code.sarif
      
    - name: Snyk Open Source monitor
      run: snyk monitor --all-projects

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-code.sarif
